auth:
  account: 陈家欢
  state_file: ./data/auth_state.json
base_url: https://lnt.xmu.edu.cn
browser:
  headless: true
course_ids:
- 87713
video:
  completion_threshold: 90
  heartbeat_interval: 60
  max_duration: 1800
